FROM public.ecr.aws/amazonlinux/amazonlinux:2023 as build

RUN mkdir /sysroot

RUN \
  dnf --releasever=$(rpm -q system-release --qf '%{VERSION}') \
  --installroot /sysroot \
  -y \
  --setopt=install_weak_deps=False \
  install bash && dnf --installroot /sysroot clean all

FROM scratch

COPY --from=build /sysroot /

WORKDIR /

ENTRYPOINT ["/bin/bash"]
