ARG VARIANT=2
FROM public.ecr.aws/amazonlinux/amazonlinux:${VARIANT}

LABEL \
    com.github.containers.toolbox="true" \
    name="amazonlinux-toolbox" \
    version="2" \
    usage="This image is meant to be used with the toolbox command." \
    summary="The base image for creating Amazon Linux 2 toolbox containers." \
    maintainer="Adam Kaminski <adam@adamkaminski.com>"

COPY packages extra-packages missing-docs /

RUN \
    sed -i '/tsflags=nodocs/d' /etc/yum.conf ; \
    yum -y install $(<packages) && \
    amazon-linux-extras install -y $(<extra-packages) && \
    yum -y reinstall $(<missing-docs) && \
    yum -y upgrade && \
    yum clean all ; \
    sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers && \
    echo 'Defaults lecture="never"' | tee /etc/sudoers.d/disable-sudo-lecture ; \
    echo VARIANT_ID=container | tee -a /etc/os-release && \
    ln -s /etc/os-release /usr/lib/os-release ; \
    rm -f /{packages,extra-packages,missing-docs} ;
